routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['verify' => true]);

Route::post('/users/{user}/avatar', 'UserAvatarController')->whereNumber('id');

Route::name('threads.')->prefix('threads')->group(function () {
    Route::get('/search', 'SearchController@show')->name('search');
    Route::get('/', 'ThreadController@index')->name('index');
    Route::post('/', 'ThreadController@store')->name('store')->middleware('verified');
    Route::get('/create', 'ThreadController@create')->name('create');
    Route::get('/{channel}/{thread}', 'ThreadController@show')->name('show');
    Route::patch('/{channel}/{thread}', 'ThreadController@update')->name('update');
});

Route::prefix('threads')->group(function () {
    Route::delete('/{channel}/{thread}', 'ThreadController@destroy');
    Route::get('/{channel}', 'ThreadController@index');
    Route::get('/{channel}/{thread}/replies', 'ReplyController@index');
    Route::post('/{channel}/{thread}/replies', 'ReplyController@store');
    Route::post('/{channel}/{thread}/subscriptions', 'ThreadSubscriptionController@store');
    Route::delete('/{channel}/{thread}/subscriptions', 'ThreadSubscriptionController@destroy');
});

Route::name('threads.')->prefix('locked-threads')->group(function () {
    Route::post('/{thread}', 'LockedThreadController@store')->name('lock');
    Route::delete('/{thread}', 'LockedThreadController@destroy')->name('unlock');
});

Route::prefix('replies')->group(function () {
    Route::patch('/{reply}', 'ReplyController@update');
    Route::delete('/{reply}', 'ReplyController@destroy')->name('replies.destroy');
    Route::post('/{reply}/favorites', 'FavoriteController@store');
    Route::delete('/{reply}/favorites', 'FavoriteController@destroy');
    Route::post('/{reply}/best', 'BestReplyController@store')->name('bestReplies.store');
});

Route::prefix('profiles')->group(function () {
    Route::get('/{user}', 'ProfileController@show')->name('profile');
    Route::get('/{user}/notifications', 'UserNotificationController@index');
    Route::delete('/{user}/notifications/{notification}', 'UserNotificationController@destroy');
});

Route::get('/sitemap.xml', 'SitemapController')->name('sitemap.index');
Route::get('/sitemap/threads.xml', 'ThreadSitemapController@index')->name('sitemap.threads.index');
Route::get('/sitemap/threads/{date}.xml', 'ThreadSitemapController@show')
    ->name('sitemap.threads.show')
    ->where('date', '[0-9]{4}-[0-9]{2}');

app/Models/Thread.php
<?php

namespace App\Models;

use App\Events\ThreadReceivedNewReply;
use Exception;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Laravel\Scout\Searchable;
use Stevebauman\Purify\Facades\Purify;

/**
 * App\Models\Thread
 *
 * @property int $id
 * @property string|null $slug
 * @property int $user_id
 * @property int $channel_id
 * @property-read int|null $replies_count
 * @property int $visits
 * @property string $title
 * @property string $body
 * @property int|null $best_reply_id
 * @property bool $locked
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Activity[] $activity
 * @property-read int|null $activity_count
 * @property-read \App\Models\Channel $channel
 * @property-read \App\Models\User $creator
 * @property-read mixed $is_subscribed_to
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Reply[] $replies
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ThreadSubscription[] $subscriptions
 * @property-read int|null $subscriptions_count
 * @method static \Illuminate\Database\Eloquent\Builder|Thread filter($filters)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Thread newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Thread query()
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereBestReplyId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereChannelId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereLocked($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereRepliesCount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereUserId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Thread whereVisits($value)
 * @mixin \Eloquent
 */
class Thread extends Model
{
    use HasFactory, RecordsActivity, Searchable;

    protected $guarded = [];

    protected $with = ['creator', 'channel'];

    protected $appends = ['isSubscribedTo'];

    protected $casts = [
        'locked' => 'boolean'
    ];

    protected static function boot()
    {
        parent::boot();

        static::created(function ($thread) {
            $thread->update(['slug' => $thread->title]);
        });

        static::deleting(function ($thread) {
            $thread->replies->each->delete();
        });
    }

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->slug}";
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    /**
     * @param array $reply
     * @return Model
     * @throws Exception
     */
    public function addReply(array $reply)
    {
        $reply = $this->replies()->create($reply);

        /** @var Reply $reply */
        event(new ThreadReceivedNewReply($reply));

        return $reply;
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query, $this);
    }

    public function subscribe($userId = null)
    {
        $this->subscriptions()->create([
            'user_id' => $userId ?: auth()->id()
        ]);

        return $this;
    }

    public function subscriptions()
    {
        return $this->hasMany(ThreadSubscription::class);
    }

    public function unsubscribe($userId = null)
    {
        $this->subscriptions()->where('user_id', $userId ?: auth()->id())->delete();
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->subscriptions()
            ->where('user_id', auth()->id())
            ->exists();
    }

    public function hasUpdatesFor($user)
    {
        $key = $user->visitedThreadCacheKey($this);

        try {
            return $this->updated_at > cache($key);
        } catch (Exception $e) {
        }
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setSlugAttribute($value)
    {
        $slug = Str::slug($value);

        while (static::whereSlug($slug)->exists()) {
            $slug = "{$slug}-{$this->id}";
        }

        $this->attributes['slug'] = $slug;
    }

    public function markBestReply(Reply $reply)
    {
        $this->update(['best_reply_id' => $reply->id]);
    }

    public function toSearchableArray()
    {
        return $this->toArray() + ['path' => $this->path()];
    }

    public function getBodyAttribute($body)
    {
        return Purify::clean($body);
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Filters\ThreadFilters;
use App\Http\Requests\CreateThreadRequest;
use App\Http\Requests\UpdateThreadRequest;
use App\Models\{Channel, Thread, Trending};
use Exception;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;

class ThreadController extends Controller
{
    /**
     * ThreadController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @param Trending $trending
     * @return Application|Factory|Response|View
     */
    public function index(Channel $channel, ThreadFilters $filters, Trending $trending)
    {
        $threads = $this->getThreads($filters, $channel);

        if (request()->wantsJson()) {
            return $threads;
        }

        return view('threads.index', [
            'threads' => $threads,
            'trending' => $trending->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateThreadRequest $request
     * @return Application|RedirectResponse|Response|Redirector
     */
    public function store(CreateThreadRequest $request)
    {
        $thread = Thread::create($request->validated());

        if (request()->wantsJson()) {
            return response($thread, 201);
        }

        return redirect($thread->path())->with('flash', __('messages.notifications.thread_published'));
    }

    /**
     * Display the specified resource.
     *
     * @param $channel
     * @param Thread $thread
     * @param Trending $trending
     * @return Application|Factory|Response|View
     * @throws Exception
     */
    public function show($channel, Thread $thread, Trending $trending)
    {
        if (auth()->check()) {
            auth()->user()->read($thread);
        }

        $trending->push($thread);

        $thread->increment('visits');

        return view('threads.show', compact('thread'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateThreadRequest $request
     * @param $channel
     * @param Thread $thread
     * @return Thread
     */
    public function update(UpdateThreadRequest $request, $channel, Thread $thread)
    {
        $thread->update($request->validated());

        return $thread;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $channel
     * @param Thread $thread
     * @return Application|RedirectResponse|Response|Redirector
     * @throws AuthorizationException
     * @throws Exception
     */
    public function destroy($channel, Thread $thread)
    {
        $this->authorize('update', $thread);

        $thread->delete();

        if (request()->wantsJson()) {
            return response([], 204);
        }

        return redirect('/threads');
    }

    /**
     * @param ThreadFilters $filters
     * @param Channel $channel
     * @return mixed
     */
    protected function getThreads(ThreadFilters $filters, Channel $channel)
    {
        $threads = Thread::latest()->filter($filters);

        if ($channel->exists) {
            $threads->where('channel_id', $channel->id);
        }

        return $threads->paginate(9);
    }
}

resources/views/threads/_body.blade.php
<div v-if="! editing">
    <h1 class="display-4 font-italic" v-text="title"></h1>
    <p>
        <img class="mr-1 rounded-circle" src="{{ $thread->creator->avatar_path }}" width="40" height="40" alt="{{ $thread->creator->name }}">
        <a href="{{ route('profile', $thread->creator) }}">{{ $thread->creator->name }}</a>,
        <small class="text-muted">{{ $thread->created_at->diffForHumans() }}</small>
    </p>

    <button class="float-right btn btn-outline-danger btn-sm" v-if="authorize('owns', thread)" @click="editing = true">{{ __('messages.actions.edit') }}</button>

    <p class="lead my-3" v-html="body"></p>
</div>

<div v-else>
    <label for="title">{{ __('messages.thread.title') }}</label>
    <input id="title" class="form-control mb-3" type="text" v-model="form.title" required>
    <label for="body">{{ __('messages.thread.body') }}</label>

    <wysiwyg v-model="form.body"></wysiwyg>

    @can('update', $thread)
        <div class="btn-group float-right" role="group" aria-label="Basic example">
            <button class="btn btn-primary btn-sm" @click="update">{{ __('messages.actions.update') }}</button>
            <button class="btn btn-warning btn-sm" @click="resetForm">{{ __('messages.actions.cancel') }}</button>

            <form method="post" action="{{ $thread->path() }}">
                @csrf
                @method('delete')

                <button class="btn btn-danger btn-sm" type="submit">
                    {{ __('messages.thread.delete') }}
                </button>
            </form>
        </div>
    @endcan

    <div class="clearfix mt-1 mb-1"></div>
</div>

resources/views/threads/_list.blade.php
@forelse ($threads as $thread)
    <div class="col-md-4">
        <div class="media">

            @if ($thread->creator->avatar_path)
                <img class="mr-3 rounded-circle" src="{{ $thread->creator->avatar_path }}" width="40" height="40" alt="">
            @endif

            <div class="media-body">
                <h5 class="mt-2">
                    <a href="{{ $thread->path() }}">
                        @if (auth()->check() && $thread->hasUpdatesFor(auth()->user()))
                            <strong>
                                {{ $thread->title }}
                            </strong>
                        @else
                            {{ $thread->title }}
                        @endif
                    </a>
                </h5>
                <p class="small text-muted">
                    {{ __('messages.thread.posted_by') }} <a href="{{ route('profile', $thread->creator) }}">{{ $thread->creator->name }}</a>,
                    {{ $thread->created_at->diffForHumans() }}
                </p>
                {!! $thread->body !!}
                <p class="small text-muted">
                    {{ $thread->replies_count }} {{ Str::plural('reply', $thread->replies_count) }},
                    {{ $thread->visits }} {{ Str::plural('visit', $thread->visits) }}
                </p>
            </div>
        </div>
    </div>
@empty
    <div class="alert alert-light" role="alert">
        {{ __('messages.thread.no_results') }}
    </div>
@endforelse

resources/views/threads/create.blade.php
@extends('layouts.app')

@push('title', ' - ' . __('messages.nav.new_thread'))

@section('header')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.0/trix.min.css" integrity="sha512-5m1IeUDKtuFGvfgz32VVD0Jd/ySGX7xdLxhqemTmThxHdgqlgPdupWoSN8ThtUSLpAGBvA8DY2oO7jJCrGdxoA==" crossorigin="anonymous">
@endsection

@section('breadcrumbs', Breadcrumbs::render('new_thread'))

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('messages.thread.create') }}</div>
                    <div class="card-body">

                        @if (count($errors))
                            <div class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    {{ $error }}<br>
                                @endforeach
                            </div>
                        @endif

                        <form id="create_form" method="post" action="{{ route('threads.store') }}">
                            @csrf
                            <div class="form-group">
                                <label for="channel_id">{{ __('messages.thread.choose_channel') }}</label>
                                <select class="form-select" name="channel_id" id="channel_id" required>
                                    <option value="">{{ __('messages.thread.choose_one') }}...</option>

                                    @foreach ($channels as $channel)
                                        <option value="{{ $channel->id }}"{{ old('channel_id') == $channel->id ? ' selected' : '' }}>{{ $channel->name }}</option>
                                    @endforeach

                                </select>
                            </div>
                            <div class="form-group">
                                <label for="title">{{ __('messages.thread.title') }}</label>
                                <input type="text" name="title" id="title" class="form-control" value="{{ old('title') }}" required>
                            </div>
                            <div class="form-group">
                                <label for="body">{{ __('messages.thread.body') }}</label>
                                <wysiwyg name="body" value="{{ old('body') }}"></wysiwyg>
                            </div>
                            <button class="btn btn-primary mt-2 g-recaptcha"
                                    data-sitekey="{{ env('RECAPTCHA_SITE_KEY') }}"
                                    data-callback="onSubmit"
                                    data-action="submit">{{ __('messages.thread.publish') }}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer')
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <script>
        function onSubmit(token) {
            document.getElementById("create_form").submit();
        }
    </script>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@push('title', ' - ' . __('messages.nav.all_threads'))

@section('breadcrumbs', Breadcrumbs::render('threads', Request::getQueryString()))

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <div class="row">
                    @include('threads._list')

                    {{ $threads->links() }}
                </div>
            </div>
            <div class="col-md-3">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    {{ __('messages.nav.search') }}
                </h4>
                <form class="mb-3" method="get" action="{{ route('threads.search') }}">
                    @csrf
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="{{ __('messages.nav.search_smth') }}..." name="q">
                        <button class="btn btn-secondary" type="submit">{{ __('messages.nav.search') }}</button>
                    </div>
                </form>

                @if ($count = count($trending))
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">{{ __('messages.nav.trending_threads') }}</span>
                        <span class="badge bg-secondary rounded-pill">{{ $count }}</span>
                    </h4>
                    <ul class="list-group mb-3">
                        @foreach ($trending as $thread)
                            <li class="list-group-item d-flex justify-content-between">
                                <a href="{{ url($thread['path']) }}">
                                    {{ $thread['title'] }}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                @endif

            </div>
        </div>
    </div>
@endsection

resources/views/threads/search.blade.php
@extends('layouts.app')

@push('title', ' - ' . __('messages.nav.search'))

@section('breadcrumbs', Breadcrumbs::render('search'))

@section('content')
    <div class="container">
        <instant-search
            app-id="{{ config('scout.algolia.id') }}"
            api-key="{{ config('scout.algolia.key') }}"
            q="{{ request('q') }}"
        ></instant-search>
    </div>
@endsection

resources/views/threads/show.blade.php
@extends('layouts.app')

@push('title', ' - ' . $thread->title)

@section('header')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.0/trix.min.css" integrity="sha512-5m1IeUDKtuFGvfgz32VVD0Jd/ySGX7xdLxhqemTmThxHdgqlgPdupWoSN8ThtUSLpAGBvA8DY2oO7jJCrGdxoA==" crossorigin="anonymous">
@endsection

@section('breadcrumbs', Breadcrumbs::render('thread', $thread))

@section('content')
    <thread-view :thread="{{ $thread }}" inline-template>
        <div class="container">
            <div class="row">

                <div class="col-md-8" v-cloak>
                    @include('threads._body')

                    <replies @added="repliesCount++" @removed="repliesCount--"></replies>
                </div>

                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">
                                {!! __('messages.thread.info', [
                                    'date' => $thread->created_at->diffForHumans(),
                                    'author' => '<a href="' . route('profile', $thread->creator) . '">' . $thread->creator->name . '</a>',
                                    'replies' => '<span v-text="repliesCount"></span> ' . Str::plural('comment', $thread->replies->count())
                                ]) !!}
                            </p>
                            <p>
                                <subscribe-button :active="@json($thread->isSubscribedTo)" v-if="signedIn"></subscribe-button>

                                <button class="btn btn-outline-danger" v-if="authorize('isAdmin')" @click="toggleLock" v-text="locked ? '{{ __('messages.thread.unlock') }}' : '{{ __('messages.thread.lock') }}'"></button>
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </thread-view>
@endsection