routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['verify' => true]);

Route::post('/users/{user}/avatar', 'UserAvatarController')->whereNumber('id');

Route::name('threads.')->prefix('threads')->group(function () {
    Route::get('/search', 'SearchController@show')->name('search');
    Route::get('/', 'ThreadController@index')->name('index');
    Route::post('/', 'ThreadController@store')->name('store')->middleware('verified');
    Route::get('/create', 'ThreadController@create')->name('create');
    Route::get('/{channel}/{thread}', 'ThreadController@show')->name('show');
    Route::patch('/{channel}/{thread}', 'ThreadController@update')->name('update');
});

Route::prefix('threads')->group(function () {
    Route::delete('/{channel}/{thread}', 'ThreadController@destroy');
    Route::get('/{channel}', 'ThreadController@index');
    Route::get('/{channel}/{thread}/replies', 'ReplyController@index');
    Route::post('/{channel}/{thread}/replies', 'ReplyController@store');
    Route::post('/{channel}/{thread}/subscriptions', 'ThreadSubscriptionController@store');
    Route::delete('/{channel}/{thread}/subscriptions', 'ThreadSubscriptionController@destroy');
});

Route::name('threads.')->prefix('locked-threads')->group(function () {
    Route::post('/{thread}', 'LockedThreadController@store')->name('lock');
    Route::delete('/{thread}', 'LockedThreadController@destroy')->name('unlock');
});

Route::prefix('replies')->group(function () {
    Route::patch('/{reply}', 'ReplyController@update');
    Route::delete('/{reply}', 'ReplyController@destroy')->name('replies.destroy');
    Route::post('/{reply}/favorites', 'FavoriteController@store');
    Route::delete('/{reply}/favorites', 'FavoriteController@destroy');
    Route::post('/{reply}/best', 'BestReplyController@store')->name('bestReplies.store');
});

Route::prefix('profiles')->group(function () {
    Route::get('/{user}', 'ProfileController@show')->name('profile');
    Route::get('/{user}/notifications', 'UserNotificationController@index');
    Route::delete('/{user}/notifications/{notification}', 'UserNotificationController@destroy');
});

Route::get('/sitemap.xml', 'SitemapController')->name('sitemap.index');
Route::get('/sitemap/threads.xml', 'ThreadSitemapController@index')->name('sitemap.threads.index');
Route::get('/sitemap/threads/{date}.xml', 'ThreadSitemapController@show')
    ->name('sitemap.threads.show')
    ->where('date', '[0-9]{4}-[0-9]{2}');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}@stack('title')</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @yield('header')
</head>
<body>
    <div id="app">
        @include('layouts.nav')

        <nav aria-label="breadcrumb">
            @yield('breadcrumbs')
        </nav>

        <main class="mt-3 py-4">
            @yield('content')
        </main>

        <flash message="{{ session('flash') }}"></flash>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script>
        window.App = @json([
            'default_locale' => config('app.locale'),
            'fallback_locale' => config('app.fallback_locale'),
            'user' => Auth::user()
        ]);
    </script>

    @yield('footer')
</body>
</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('messages.nav.toggle') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link{{ Request::is('threads') && Request::getQueryString() == '' ? ' active' : '' }}" href="{{ route('threads.index') }}">{{ __('messages.nav.all_threads') }}</a>
                </li>

                @auth
                    <li class="nav-item">
                        <a class="nav-link{{ Request::getQueryString() == 'by=' . auth()->user()->slug ? ' active' : '' }}" href="{{ route('threads.index') }}?by={{ auth()->user()->slug }}">{{ __('messages.nav.my_threads') }}</a>
                    </li>
                @endauth

                <li class="nav-item">
                    <a class="nav-link{{ Request::getQueryString() == 'popular=1' ? ' active' : '' }}" href="{{ route('threads.index') }}?popular=1">{{ __('messages.nav.popular_threads') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{{ Request::getQueryString() == 'unanswered=1' ? ' active' : '' }}" href="{{ route('threads.index') }}?unanswered=1">{{ __('messages.nav.unanswered_threads') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link{{ Request::is('threads/create') ? ' active' : '' }}" href="{{ route('threads.create') }}">{{ __('messages.nav.new_thread') }}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ __('messages.nav.channels') }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">

                        @foreach ($channels as $channel)
                            <a class="dropdown-item" href="/threads/{{ $channel->slug }}">{{ $channel->name }}</a>
                        @endforeach

                    </div>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('messages.nav.login') }}</a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('messages.nav.register') }}</a>
                        </li>
                    @endif
                @else
                    <user-notifications></user-notifications>

                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ auth()->user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a href="{{ route('profile', auth()->user()) }}" class="dropdown-item">
                                {{ __('messages.nav.profile') }}
                            </a>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                {{ __('messages.nav.logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>